[2023-12-11 18:56:45,737] INFO _log() L186   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:56:57,906] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:56:57,912] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:56:57] "[33mGET /partidas HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:57:11,377] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:57:11,385] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:57:11] "[33mGET /partidas HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:57:17,974] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:57:17,982] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:57:17] "[33mGET /partidas?homeTeam=America-MG HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:57:18,038] ERROR log_exception() L1449 Exception on /partida [POST] - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py L1449
Traceback (most recent call last):
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1519, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_cors\extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1517, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\app.py", line 1503, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\scaffold.py", line 191, in wrapper
    resp = _do_wrapper(
           ^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask_openapi3\do_wrapper.py", line 135, in _do_wrapper
    response = func(**request_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py", line 83, in predict
    scaler = Model.carrega_modelo(ml_scaler)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\model\modelo.py", line 17, in carrega_modelo
    model = pickle.load(open(path, 'rb'))
                        ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'ml_model/scaler.pkl'
[2023-12-11 18:57:18,071] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:57:18] "[35m[1mPOST /partida HTTP/1.1[0m" 500 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:57:19,486] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:57:19,502] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:57:19] "[33mGET /partidas HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:57:48,831] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\Dados\\Pós\\Github Pós\\mvp-qualidade-seguranca-sistemas-inteligentes\\MVP\\api\\MVP_SPRINT_IV_API\\app.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:57:48,875] INFO _log() L186   * Detected change in 'C:\\Users\\Pedro Serrano\\Dados\\Pós\\Github Pós\\mvp-qualidade-seguranca-sistemas-inteligentes\\MVP\\api\\MVP_SPRINT_IV_API\\app.py', reloading - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:57:51,586] INFO _log() L186   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:58:04,561] INFO _log() L186   * Restarting with watchdog (windowsapi) - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:00,056] WARNING get_partidas() L56   Não há partidas cadastradas na base :/ - call_trace=C:\Users\Pedro Serrano\Dados\Pós\Github Pós\mvp-qualidade-seguranca-sistemas-inteligentes\MVP\api\MVP_SPRINT_IV_API\app.py L56  
[2023-12-11 18:59:00,168] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:00] "[33mGET /partidas?homeTeam=Vasco HTTP/1.1[0m" 404 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:00,552] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:00] "POST /partida HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:01,907] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:01] "GET /partidas HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:08,396] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:08] "GET /partidas HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:24,785] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:24] "GET /partidas?homeTeam=America-RN HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:24,890] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:24] "POST /partida HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:26,232] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:26] "GET /partidas HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:39,156] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:39] "GET /partidas?homeTeam=Flamengo HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:39,257] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:39] "POST /partida HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:40,593] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:40] "GET /partidas HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:43,799] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:43] "OPTIONS /partida?mandante=Flamengo&visitante=America-RN HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:43,881] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:43] "DELETE /partida?mandante=Flamengo&visitante=America-RN HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:58,191] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:58] "GET /partidas?homeTeam=Bahia HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:58,290] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:58] "POST /partida HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
[2023-12-11 18:59:59,543] INFO _log() L186  127.0.0.1 - - [11/Dec/2023 18:59:59] "GET /partidas HTTP/1.1" 200 - - call_trace=C:\Users\Pedro Serrano\AppData\Local\Programs\Python\Python311\Lib\site-packages\werkzeug\_internal.py L186 
